import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import type { Client } from "./useClients";

export interface Quote {
  id: string;
  quote_number: string;
  client_id: string;
  canal_entrada: string | null;
  tipo_evento: string | null;
  data_status: string;
  data_evento: string | null;
  dia_semana: string | null;
  ano_evento: string | null;
  n_convidados: number;
  pacote: string;
  menu_buffet: string | null;
  valor_total: number;
  validade: string | null;
  status: string;
  observacoes_internas: string | null;
  observacoes_cliente: string | null;
  percentual_sinal: number;
  valor_sinal: number;
  numero_parcelas: number;
  dia_vencimento: number;
  parcelas_json: any;
  extras_json: any;
  created_at: string;
  updated_at: string;
  client?: Client;
}

export interface QuoteInsert {
  quote_number?: string; // auto-generated by trigger
  client_id: string;
  canal_entrada?: string | null;
  tipo_evento?: string | null;
  data_status?: string;
  data_evento?: string | null;
  dia_semana?: string | null;
  ano_evento?: string | null;
  n_convidados: number;
  pacote: string;
  menu_buffet?: string | null;
  valor_total: number;
  validade?: string | null;
  status?: string;
  observacoes_internas?: string | null;
  observacoes_cliente?: string | null;
  percentual_sinal?: number;
  valor_sinal?: number;
  numero_parcelas?: number;
  dia_vencimento?: number;
  parcelas_json?: any;
  extras_json?: any;
}

export function useQuotes() {
  const [quotes, setQuotes] = useState<Quote[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchQuotes = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("quotes")
      .select(`
        *,
        client:clients(*)
      `)
      .order("created_at", { ascending: false });

    if (error) {
      toast({
        title: "Erro ao carregar orçamentos",
        description: error.message,
        variant: "destructive",
      });
    } else {
      setQuotes(data || []);
    }
    setLoading(false);
  };

  const createQuote = async (quote: QuoteInsert): Promise<Quote | null> => {
    // quote_number is auto-generated by trigger, but we need to pass empty string
    const insertData = { ...quote, quote_number: "" };
    
    const { data, error } = await supabase
      .from("quotes")
      .insert([insertData])
      .select(`
        *,
        client:clients(*)
      `)
      .single();

    if (error) {
      toast({
        title: "Erro ao criar orçamento",
        description: error.message,
        variant: "destructive",
      });
      return null;
    }

    setQuotes((prev) => [data, ...prev]);
    toast({
      title: "Orçamento criado!",
      description: `Orçamento ${data.quote_number} foi criado com sucesso.`,
    });
    return data;
  };

  const updateQuote = async (id: string, updates: Partial<QuoteInsert>): Promise<boolean> => {
    const { error } = await supabase
      .from("quotes")
      .update(updates)
      .eq("id", id);

    if (error) {
      toast({
        title: "Erro ao atualizar orçamento",
        description: error.message,
        variant: "destructive",
      });
      return false;
    }

    await fetchQuotes();
    toast({
      title: "Orçamento atualizado!",
    });
    return true;
  };

  const updateQuoteStatus = async (id: string, status: string): Promise<boolean> => {
    const { error } = await supabase
      .from("quotes")
      .update({ status })
      .eq("id", id);

    if (error) {
      toast({
        title: "Erro ao atualizar status",
        description: error.message,
        variant: "destructive",
      });
      return false;
    }

    setQuotes((prev) =>
      prev.map((q) => (q.id === id ? { ...q, status } : q))
    );
    return true;
  };

  const deleteQuote = async (id: string): Promise<boolean> => {
    const { error } = await supabase
      .from("quotes")
      .delete()
      .eq("id", id);

    if (error) {
      toast({
        title: "Erro ao excluir orçamento",
        description: error.message,
        variant: "destructive",
      });
      return false;
    }

    setQuotes((prev) => prev.filter((q) => q.id !== id));
    toast({
      title: "Orçamento excluído!",
    });
    return true;
  };

  const getQuoteById = async (id: string): Promise<Quote | null> => {
    const { data, error } = await supabase
      .from("quotes")
      .select(`
        *,
        client:clients(*)
      `)
      .eq("id", id)
      .maybeSingle();

    if (error) {
      toast({
        title: "Erro ao carregar orçamento",
        description: error.message,
        variant: "destructive",
      });
      return null;
    }

    return data;
  };

  const getQuoteByNumber = async (quoteNumber: string): Promise<Quote | null> => {
    const { data, error } = await supabase
      .from("quotes")
      .select(`
        *,
        client:clients(*)
      `)
      .eq("quote_number", quoteNumber)
      .maybeSingle();

    if (error) {
      toast({
        title: "Erro ao carregar orçamento",
        description: error.message,
        variant: "destructive",
      });
      return null;
    }

    return data;
  };

  useEffect(() => {
    fetchQuotes();
  }, []);

  return {
    quotes,
    loading,
    fetchQuotes,
    createQuote,
    updateQuote,
    updateQuoteStatus,
    deleteQuote,
    getQuoteById,
    getQuoteByNumber,
  };
}
