import { useState, useEffect } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import { z } from "zod";
import { getSafeErrorMessage } from "@/lib/errorHandler";
import type { Client } from "./useClients";

export interface Quote {
  id: string;
  quote_number: string;
  client_id: string;
  canal_entrada: string | null;
  tipo_evento: string | null;
  data_status: string;
  data_evento: string | null;
  dia_semana: string | null;
  ano_evento: string | null;
  n_convidados: number;
  pacote: string;
  menu_buffet: string | null;
  valor_total: number;
  validade: string | null;
  status: string;
  observacoes_internas: string | null;
  observacoes_cliente: string | null;
  percentual_sinal: number;
  valor_sinal: number;
  numero_parcelas: number;
  dia_vencimento: number;
  parcelas_json: any;
  extras_json: any;
  created_at: string;
  updated_at: string;
  client?: Client;
}

export interface QuoteInsert {
  quote_number?: string; // auto-generated by trigger
  client_id: string;
  canal_entrada?: string | null;
  tipo_evento?: string | null;
  data_status?: string;
  data_evento?: string | null;
  dia_semana?: string | null;
  ano_evento?: string | null;
  n_convidados: number;
  pacote: string;
  menu_buffet?: string | null;
  valor_total: number;
  validade?: string | null;
  status?: string;
  observacoes_internas?: string | null;
  observacoes_cliente?: string | null;
  percentual_sinal?: number;
  valor_sinal?: number;
  numero_parcelas?: number;
  dia_vencimento?: number;
  parcelas_json?: any;
  extras_json?: any;
}

// Extra item validation schema
const extraItemSchema = z.object({
  id: z.string(),
  description: z.string().max(200, "Descrição do extra muito longa"),
  value: z.number().min(0, "Valor não pode ser negativo"),
  perGuest: z.boolean().optional(),
});

// Parcela validation schema
const parcelaSchema = z.object({
  numero: z.number().int().min(1),
  valor: z.number().min(0),
  vencimento: z.string(),
});

// Zod validation schema for quote data
const quoteSchema = z.object({
  client_id: z.string().uuid("Cliente inválido"),
  canal_entrada: z.string().max(100).optional().nullable(),
  tipo_evento: z.string().max(100).optional().nullable(),
  data_status: z.string().max(50).optional(),
  data_evento: z.string().optional().nullable(),
  dia_semana: z.string().max(20).optional().nullable(),
  ano_evento: z.string().max(10).optional().nullable(),
  n_convidados: z.number()
    .int("Número de convidados deve ser inteiro")
    .min(1, "Mínimo 1 convidado")
    .max(2000, "Número de convidados muito alto"),
  pacote: z.string()
    .min(1, "Pacote é obrigatório")
    .max(100, "Nome do pacote muito longo"),
  menu_buffet: z.string().max(100).optional().nullable(),
  valor_total: z.number()
    .min(0, "Valor total não pode ser negativo")
    .max(10000000, "Valor total muito alto"),
  validade: z.string().optional().nullable(),
  status: z.string().max(50).optional(),
  observacoes_internas: z.string().max(2000, "Observações internas muito longas").optional().nullable(),
  observacoes_cliente: z.string().max(2000, "Observações do cliente muito longas").optional().nullable(),
  percentual_sinal: z.number()
    .int()
    .min(0, "Percentual não pode ser negativo")
    .max(100, "Percentual máximo é 100")
    .optional(),
  valor_sinal: z.number()
    .min(0, "Valor do sinal não pode ser negativo")
    .optional(),
  numero_parcelas: z.number()
    .int()
    .min(1, "Mínimo 1 parcela")
    .max(48, "Máximo 48 parcelas")
    .optional(),
  dia_vencimento: z.number()
    .int()
    .refine(val => [5, 10, 15, 20, 25].includes(val), "Dia de vencimento inválido")
    .optional(),
  parcelas_json: z.array(parcelaSchema).optional().nullable(),
  extras_json: z.array(extraItemSchema).optional().nullable(),
});

export function useQuotes() {
  const [quotes, setQuotes] = useState<Quote[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchQuotes = async () => {
    setLoading(true);
    const { data, error } = await supabase
      .from("quotes")
      .select(`
        *,
        client:clients(*)
      `)
      .order("created_at", { ascending: false });

    if (error) {
      toast({
        title: "Erro ao carregar orçamentos",
        description: getSafeErrorMessage(error, "fetchQuotes"),
        variant: "destructive",
      });
    } else {
      setQuotes(data || []);
    }
    setLoading(false);
  };

  const createQuote = async (quote: QuoteInsert): Promise<Quote | null> => {
    // Validate quote data
    const validationResult = quoteSchema.safeParse(quote);
    if (!validationResult.success) {
      const firstError = validationResult.error.errors[0];
      toast({
        title: "Dados inválidos",
        description: firstError.message,
        variant: "destructive",
      });
      return null;
    }

    // quote_number is auto-generated by trigger, but we need to pass empty string
    const validatedData = validationResult.data as QuoteInsert;
    const insertData = { ...validatedData, quote_number: "" };
    
    const { data, error } = await supabase
      .from("quotes")
      .insert([insertData])
      .select(`
        *,
        client:clients(*)
      `)
      .single();

    if (error) {
      toast({
        title: "Erro ao criar orçamento",
        description: getSafeErrorMessage(error, "createQuote"),
        variant: "destructive",
      });
      return null;
    }

    setQuotes((prev) => [data, ...prev]);
    toast({
      title: "Orçamento criado!",
      description: `Orçamento ${data.quote_number} foi criado com sucesso.`,
    });
    return data;
  };

  const updateQuote = async (id: string, updates: Partial<QuoteInsert>): Promise<boolean> => {
    // Validate update data (partial validation)
    const partialSchema = quoteSchema.partial();
    const validationResult = partialSchema.safeParse(updates);
    if (!validationResult.success) {
      const firstError = validationResult.error.errors[0];
      toast({
        title: "Dados inválidos",
        description: firstError.message,
        variant: "destructive",
      });
      return false;
    }

    const validatedData = validationResult.data as Partial<QuoteInsert>;
    const { error } = await supabase
      .from("quotes")
      .update(validatedData)
      .eq("id", id);

    if (error) {
      toast({
        title: "Erro ao atualizar orçamento",
        description: getSafeErrorMessage(error, "updateQuote"),
        variant: "destructive",
      });
      return false;
    }

    await fetchQuotes();
    toast({
      title: "Orçamento atualizado!",
    });
    return true;
  };

  const updateQuoteStatus = async (id: string, status: string): Promise<boolean> => {
    // Validate status
    const statusSchema = z.string().max(50);
    const validationResult = statusSchema.safeParse(status);
    if (!validationResult.success) {
      toast({
        title: "Dados inválidos",
        description: "Status inválido",
        variant: "destructive",
      });
      return false;
    }

    const { error } = await supabase
      .from("quotes")
      .update({ status })
      .eq("id", id);

    if (error) {
      toast({
        title: "Erro ao atualizar status",
        description: getSafeErrorMessage(error, "updateQuoteStatus"),
        variant: "destructive",
      });
      return false;
    }

    setQuotes((prev) =>
      prev.map((q) => (q.id === id ? { ...q, status } : q))
    );
    return true;
  };

  const deleteQuote = async (id: string): Promise<boolean> => {
    const { error } = await supabase
      .from("quotes")
      .delete()
      .eq("id", id);

    if (error) {
      toast({
        title: "Erro ao excluir orçamento",
        description: getSafeErrorMessage(error, "deleteQuote"),
        variant: "destructive",
      });
      return false;
    }

    setQuotes((prev) => prev.filter((q) => q.id !== id));
    toast({
      title: "Orçamento excluído!",
    });
    return true;
  };

  const getQuoteById = async (id: string): Promise<Quote | null> => {
    const { data, error } = await supabase
      .from("quotes")
      .select(`
        *,
        client:clients(*)
      `)
      .eq("id", id)
      .maybeSingle();

    if (error) {
      toast({
        title: "Erro ao carregar orçamento",
        description: getSafeErrorMessage(error, "getQuoteById"),
        variant: "destructive",
      });
      return null;
    }

    return data;
  };

  const getQuoteByNumber = async (quoteNumber: string): Promise<Quote | null> => {
    const { data, error } = await supabase
      .from("quotes")
      .select(`
        *,
        client:clients(*)
      `)
      .eq("quote_number", quoteNumber)
      .maybeSingle();

    if (error) {
      toast({
        title: "Erro ao carregar orçamento",
        description: getSafeErrorMessage(error, "getQuoteByNumber"),
        variant: "destructive",
      });
      return null;
    }

    return data;
  };

  useEffect(() => {
    fetchQuotes();
  }, []);

  return {
    quotes,
    loading,
    fetchQuotes,
    createQuote,
    updateQuote,
    updateQuoteStatus,
    deleteQuote,
    getQuoteById,
    getQuoteByNumber,
  };
}
